Update data manager
julius-gummersbach/cae-performance-data-monitoring-tool pull request #54
Opened 2023-02-01 08:18 UTC by JonasBoecker

2023-02-01 09:22 UTC, SuperNova2712 approved these changes

2023-02-01 13:47 UTC, sburk6 approved these changes

2023-02-02 08:18 UTC, julius-gummersbach requested changes

2023-02-02 08:18 UTC, julius-gummersbach commented on core/datastore/DataManager.hpp
> +  class DataManager {
Documentation missing

2023-02-07 09:38 UTC, sburk6 approved these changes

2023-02-09 08:43 UTC, julius-gummersbach commented on core/datastore/DataManager.hpp
> +  class DataManager {
ok later I guess

2023-02-09 08:43 UTC, julius-gummersbach approved these changes

2023-02-09 09:26 UTC, TomsCodingCode approved these changes

2023-02-09 09:34 UTC, merged