Create data parser
julius-gummersbach/cae-performance-data-monitoring-tool pull request #58
Opened 2023-02-01 16:24 UTC by JonasBoecker

2023-02-02 08:13 UTC, julius-gummersbach requested changes

2023-02-02 08:13 UTC, julius-gummersbach commented on core/dataprocessing/DataParser.hpp
> +    static bool parseThreadInfo(const json &object,
Documentation missing

2023-02-02 08:13 UTC, julius-gummersbach commented on core/datastore/DataManager.hpp
> +  class DataManager {
Documentation missing

2023-02-07 09:42 UTC, sburk6 approved these changes

2023-02-09 08:31 UTC, TomsCodingCode submitted a review, later dismissed

2023-02-09 08:43 UTC, julius-gummersbach commented on core/dataprocessing/DataParser.hpp
> +    static bool parseThreadInfo(const json &object,
ok later I guess

2023-02-09 08:43 UTC, julius-gummersbach commented on core/datastore/DataManager.hpp
> +  class DataManager {
ok later I guess

2023-02-09 09:26 UTC, sburk6 submitted a review, later dismissed

2023-02-09 09:41 UTC, JosiasKasemann approved these changes

2023-02-09 09:42 UTC, sburk6 approved these changes

2023-02-09 09:46 UTC, julius-gummersbach approved these changes

2023-02-09 09:47 UTC, merged